import Image from "next/image";
import { base64logo } from "../util/base64logo";

export default function Header() {
  fetch("/SSINT-AI.png")
    .then((r) => r.blob())
    .then((b) => {
      const reader = new FileReader();
      reader.onloadend = () => console.log(reader.result);
      reader.readAsDataURL(b);
    });

  return (
    <div className="relative overflow-hidden bg-white py-16 px-6">
      {/* Neural network background pattern */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2">
        {/* <Image src="/SSINT-AI.png" alt="Company Logo" width={100} height={40 } /> */}
        <Image
          src={base64logo}
          alt="Company Logo"
          width={100}
          height={40}
          
        />
      </div>

      {/* Main content */}
      <div className="relative text-center space-y-6 max-w-4xl mx-auto">
        {/* Main title */}
        <div className="space-y-4 ">
          <h1 className="text-3xl md:text-5xl font-bold text-balance">
            <span className="bg-gradient-to-r from-gray-900 via-blue-600 to-purple-600 bg-clip-text text-transparent">
              Trading Card
            </span>
            <span className="text-gray-200 mx-3">|</span>
            <span className="bg-gradient-to-r from-purple-600 via-blue-600 to-gray-900 bg-clip-text text-transparent">
              Grading Report
            </span>
          </h1>

          {/* Subtitle with tech styling */}
          <div className="flex items-center justify-center gap-3 text-gray-600">
            <div className="h-px w-8 bg-gradient-to-r from-transparent to-blue-500"></div>
            <span className="font-mono text-sm md:text-base tracking-wide">
              Report generated by{" "}
              <span className="text-blue-600 font-semibold">
                SSINT AI Grader
              </span>{" "}
              <span className="text-purple-600">V1.0</span>
            </span>
            <div className="h-px w-8 bg-gradient-to-l from-transparent to-blue-500"></div>
          </div>
        </div>
      </div>

      {/* Corner accents */}
      {/* <div className="absolute top-0 left-0 w-20 h-20 border-l-2 border-t-2 border-blue-300"></div>
      <div className="absolute top-0 right-0 w-20 h-20 border-r-2 border-t-2 border-purple-300"></div>
      <div className="absolute bottom-0 left-0 w-20 h-20 border-l-2 border-b-2 border-purple-300"></div>
      <div className="absolute bottom-0 right-0 w-20 h-20 border-r-2 border-b-2 border-blue-300"></div> */}
    </div>
  );
}
